---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-auth
  namespace: auth
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # FIXME: Change the NFS Server
    path: "/var/nfs/storage/auth"
    server: storage.fr.urantiacloud.com
    readOnly: false
